# Generated by Django 5.1.4 on 2025-01-18 17:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
