# Generated by Django 5.1.4 on 2025-01-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lecture_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollkey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
